admin:
  emails: cpwu@foxmail.com
app:
  chinese:
    name: \u6821\u56ED\u5931\u7269\u62DB\u9886\u7F51\u7AD9\u7CFB\u7EDF
max:
  upload:
    size: 4MB
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: Asia/Shanghai
  profiles:
    active: prod,dev,druid,jpa,log,mvc
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 128
      thread-name-prefix: myExecutor
system:
  email: cpwu@foxmail.com
