server:
  servlet:
    session:
      cookie:
        max-age: -1S
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm
    serialization:
      indent-output: true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: /opt/lostFound/static,/opt/lostFound/resources,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
web:
  upload-path: /opt/lostFound/resources/upload/lost-found
